name: ThirdLife
version: 0.1
main: me.vespertilo.thirdlife.ThirdLife
api-version: 1.20
authors: [ Vespertilo ]
commands:
  startsession:
    description: starts a session
    permission: op
  endsession:
    description: ends a session
    permission: op
  rollboogey:
    description: rolls a new boogeyman
    permission: op
  time:
    description: adds and removes time from a player
    permission: op